name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # mainブランチにpushされたらデプロイ実行

permissions:
  id-token: write  # OIDC認証のために必要

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリのコードを取得
      uses: actions/checkout@v4

    - name: Azure にログイン
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 依存関係をインストール
      run: |
        pip install -r requirements.txt

    - name: Azure にデプロイ
      uses: azure/webapps-deploy@v2
      with:
        app-name: "test250301"  # Azure Web App の名前を指定
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
